-- Generated by member/scripts/sync-learning-catalog.mjs from original LMR reference.
-- Apply after inner-circle.sql. Local release artifact; not applied live.
begin;
create schema if not exists circle_private;
revoke all on schema circle_private from public,anon;
grant usage on schema circle_private to authenticated;
create table if not exists circle_private.learning_catalog(
 chapter_no integer primary key,term_ids text[] not null,answers text[] not null
);
revoke all on circle_private.learning_catalog from public,anon,authenticated;
insert into circle_private.learning_catalog values
-- CATALOG_ROWS
on conflict(chapter_no) do update set term_ids=excluded.term_ids,answers=excluded.answers;
create table if not exists public.circle_learning_progress(
 user_id uuid not null references auth.users on delete cascade,
 chapter_no integer not null check(chapter_no between 1 and 10),
 reviewed_terms text[] not null default '{}',completed_at timestamptz,
 updated_at timestamptz not null default now(),primary key(user_id,chapter_no)
);
alter table public.circle_learning_progress enable row level security;
revoke all on public.circle_learning_progress from public,anon,authenticated;
grant select on public.circle_learning_progress to authenticated;
grant all on public.circle_learning_progress to service_role;
drop policy if exists circle_learning_own on public.circle_learning_progress;
create policy circle_learning_own on public.circle_learning_progress for select to authenticated using(user_id=auth.uid());
-- A narrowly scoped privileged writer is necessary: clients have SELECT only,
-- and cannot set completion timestamps or read the private answer catalog.
-- It derives its actor from auth.uid(), has no caller-supplied user ID,
-- and checks every prerequisite under one transaction lock.
create or replace function circle_private.record_learning(chapter integer,term text,checkpoint_answers text[])
returns public.circle_learning_progress language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); catalog circle_private.learning_catalog; progress public.circle_learning_progress;
begin
 if actor is null or coalesce((auth.jwt()->>'is_anonymous')::boolean,false) then raise exception 'Sign in with an LMR account'; end if;
 perform pg_advisory_xact_lock(hashtextextended(actor::text,42));
 select * into catalog from circle_private.learning_catalog where chapter_no=chapter;
 if not found then raise exception 'Unknown chapter'; end if;
 if (select count(*) from public.circle_learning_progress where user_id=actor and chapter_no<chapter and completed_at is not null) <> chapter-1 then
  raise exception 'Complete the previous chapter first';
 end if;
 if term is null and checkpoint_answers is null then raise exception 'Choose a lesson or checkpoint'; end if;
 if term is not null and not(term=any(catalog.term_ids)) then raise exception 'This lesson does not belong to the chapter'; end if;
 insert into public.circle_learning_progress(user_id,chapter_no) values(actor,chapter) on conflict do nothing;
 if term is not null then
  update public.circle_learning_progress set reviewed_terms=(select array_agg(distinct x order by x) from unnest(reviewed_terms||array[term]) x),updated_at=now() where user_id=actor and chapter_no=chapter;
 end if;
 select * into progress from public.circle_learning_progress where user_id=actor and chapter_no=chapter;
 if checkpoint_answers is not null then
  if not(catalog.term_ids <@ progress.reviewed_terms) then raise exception 'Study every lesson before the checkpoint'; end if;
  if checkpoint_answers is distinct from catalog.answers then raise exception 'Revisit the definitions and try the checkpoint again'; end if;
  update public.circle_learning_progress set completed_at=coalesce(completed_at,now()),updated_at=now() where user_id=actor and chapter_no=chapter returning * into progress;
 end if;
 return progress;
end $$;
revoke all on function circle_private.record_learning(integer,text,text[]) from public,anon;
grant execute on function circle_private.record_learning(integer,text,text[]) to authenticated;
create or replace function public.circle_record_learning(chapter integer,term text default null,checkpoint_answers text[] default null)
returns public.circle_learning_progress language sql security invoker set search_path='' as $$
 select circle_private.record_learning(chapter,term,checkpoint_answers);
$$;
revoke all on function public.circle_record_learning(integer,text,text[]) from public,anon;
grant execute on function public.circle_record_learning(integer,text,text[]) to authenticated;
commit;
