// Public product guidance. Policy documents remain drafts until owner approval.
export const provider = {
  name: "Niraj Ghorsaine",
  businessName: "LMR Capitals Ptv Lmt",
  entity: "Individual / sole trader",
  abn: "24 168 533 274",
  location: "New South Wales, Australia",
  contact: "admin@lmrcapitals.com",
};
export const policyDraftVersion = "2026-10-05-draft";
export const guideUrl = "/inner-circle/guide";
export const policyUrl = (kind) => `${guideUrl}#${["terms", "privacy", "risk", "community"].includes(kind) ? kind : "start"}`;
export const accessComparison = [
  ["Ten terminology chapters & learning progress", "Included", "Included"],
  ["Free resources & community announcements", "Included", "Included"],
  ["Live analysis: Asia, London, NY AM & NY PM", "Membership required", "Published sessions"],
  ["LMR observations, callouts, executions & achievements", "Membership required", "Included"],
  ["Member questions & answers", "Included", "Included"],
  ["Private mentorship requests", "Membership required", "Request access"],
  ["Journal Application", "Membership required", "Included"],
  ["Administrator Hub", "Administrator only", "Administrator only"],
];
export const joiningSteps = [
  { title: "Create your free account", body: "Use your name, your own email and a password of at least 12 characters. Read the account terms, privacy notice and trading risk disclosure. Membership is for adults aged 18 or older." },
  { title: "Confirm your email, then sign in", body: "Open the confirmation email from LMR and follow its link. Check spam if it does not arrive. Return to Inner Circle and sign in with the same email. Already have an LMR account? Use it instead of creating another." },
  { title: "Begin your first chapter", body: "Open LMR terminology, study Chapter 1 and complete its knowledge check to unlock the next chapter. Your dashboard keeps your place. Explore the free resources at any time." },
  { title: "Add membership when you are ready", body: "Choose Get membership, review the monthly or annual plan and accept the membership terms. Stripe shows the total, currency, any applicable tax and recurring billing details before you confirm. Creating a free account does not subscribe you." },
  { title: "Return to your paid workspace", body: "Keep the same account after checkout. Paid features open only when LMR verifies your paid subscription. If payment is still processing, refresh your membership status before attempting another purchase." },
];
export const policies = {
  terms: {
    title: "Account & membership terms", draft: true,
    introduction: "These draft terms describe the proposed Inner Circle service. New registration and paid enrollment remain closed until the policies and billing setup are approved.",
    sections: [
      { title: "Who provides the service", paragraphs: ["LMR Inner Circle is provided by Niraj Ghorsaine, an individual / sole trader operating under the registered business name LMR Capitals Ptv Lmt, ABN 24 168 533 274, in New South Wales, Australia. Contact admin@lmrcapitals.com for account, billing or service enquiries."] },
      { title: "Your account", paragraphs: ["You must be at least 18 to register. Use accurate account details and an email you control. Keep your password private and tell LMR if you suspect unauthorised access. An account is for one person; do not share, resell or transfer access.", "A free account includes LMR terminology, chapter progress, free resources, your profile and announcements available to free members. Chapter completion unlocks the next learning chapter. A free account does not create a paid subscription."] },
      { title: "What membership includes", paragraphs: ["A verified paid membership provides access to published live analysis sessions, LMR observations, callouts, executions and achievements, the Journal Application and private mentorship requests. Administrator tools are reserved for registered LMR administrators and are not included in any membership.", "Live sessions may be organised into Asia, London, NY AM and NY PM. These are session categories, not a promise that all four streams run every day. Check the published schedule and its time zone. Availability of recordings is shown for each session.", "Mentorship is an educational support request. A subscription does not automatically book a session or guarantee a particular time, response time or acceptance. LMR confirms scheduling and any separately priced service before you agree to it."] },
      { title: "Educational scope and trading risk", paragraphs: ["THE Chain Methodology, live analysis, observations, Q&A and mentorship are presented for learning and review. They do not consider your individual financial situation or objectives and are not instructions to buy, sell or copy a trade. The Journal Application records and reviews activity; it is not a brokerage service.", "Trading can result in substantial losses, including losses greater than your initial investment when leverage is involved. No profits, funded account, achievement or result is guaranteed. Read the risk disclosure before using market content. You remain responsible for your decisions."] },
      { title: "Price, recurring payments and activation", paragraphs: ["Membership is offered on a monthly or annual recurring basis. The selected Stripe checkout must show the price, currency, applicable taxes, billing interval and total before payment. There is no advertised free trial in this joining guide. Any promotion or trial applies only if its specific terms are clearly shown before you confirm.", "Confirming a recurring subscription authorises the payments described at checkout until you cancel. Paid access starts after LMR receives and verifies the subscription payment. Returning from checkout, receiving an email or clicking a success link does not itself unlock membership.", "Use your existing account for checkout. If an active or unresolved subscription is already linked to it, manage that subscription rather than creating another. Contact support if a paid invoice exists but access has not opened."] },
      { title: "Cancellation, failed payments and refunds", paragraphs: ["To request cancellation or resolve a billing problem, open Profile → Membership and use the available Stripe billing controls. If those controls are unavailable, email admin@lmrcapitals.com from your account email and include your invoice reference. Do not send card details or passwords.", "The billing confirmation must state whether cancellation takes effect immediately or at the end of the paid period. Check the membership status and access end date after any change. Failed or overdue payments can prevent paid access. Cancelling a subscription does not automatically delete your free account or request a refund.", "Refund requests are reviewed case by case. Email admin@lmrcapitals.com with your account email, invoice reference and the reason for the request. Review does not guarantee a refund. This policy does not exclude or limit rights or remedies that cannot be excluded under Australian Consumer Law, including applicable remedies for a service failure."] },
      { title: "Community, content and service changes", paragraphs: ["Follow the community guidelines. Do not harass others, share account credentials, solicit investments, distribute pirated LMR content, impersonate administrators or post private information. LMR may restrict access for abuse or security incidents and will provide a contact route for questions or review.", "LMR materials are for your personal learning. Do not redistribute paid streams, publications or learning materials without permission. Keep ownership of content you submit and grant LMR permission to use it to provide the requested service. Do not submit material you do not have permission to use.", "Maintenance, streaming issues and market conditions may affect availability. If a material membership change is proposed, LMR must explain the change and any effect on pricing or access before it applies. Nothing in these terms removes your non-excludable consumer rights."] },
      { title: "Questions and complaints", paragraphs: ["Contact admin@lmrcapitals.com with the relevant account email, dates and a description of the issue. LMR will review account, billing and service complaints. These terms operate subject to applicable Australian law and any mandatory rights that apply to you; they do not require you to waive those rights."] },
    ],
  },
  privacy: {
    title: "Privacy notice", draft: true,
    introduction: "This draft describes the information used by the current account and membership application. It must be approved before new registration opens.",
    sections: [
      { title: "Who handles your information", paragraphs: ["Niraj Ghorsaine, operating as LMR Capitals Ptv Lmt, ABN 24 168 533 274, is the service provider in New South Wales, Australia. Send privacy questions, access or correction requests to admin@lmrcapitals.com."] },
      { title: "Information you provide", paragraphs: ["Account registration uses your name, email, password and acknowledgement of the policy version. Your optional member profile can include a display name, time zone, learning description and profile photo. If you sign in with Google and it supplies a profile photo, the service can display it. You can upload a replacement, restore your Google photo or use initials. The service also stores chapter progress, saved publications, notification preferences, questions, mentorship requests and subscription status.", "The Journal Application can store trading records, accounts, reviews, notes and uploaded images that you choose to add. Avoid putting identity documents, card numbers, passwords or other people's private information into your profile, questions or uploads. Optional external integrations may send data to the service you connect; review that provider before enabling or sharing."] },
      { title: "How the information is used", paragraphs: ["The application uses this information to authenticate your account, show your learning progress, manage free or paid access, deliver requested educational support, process billing status and protect the service. Session information in your browser keeps you signed in. A device preference may remember that you dismissed the getting-started checklist.", "Notification settings control the supported in-app preferences. They do not unsubscribe you from essential security, account or billing communications. This application does not currently offer configured push or marketing email alerts through those settings."] },
      { title: "Payments and service providers", paragraphs: ["Stripe handles payment details on Stripe-hosted checkout and billing pages. LMR's membership database stores references such as customer and subscription IDs, payment status and billing periods; the joining form does not collect your full card number.", "Supabase provides account authentication, database and file storage. The configured database region is Singapore. Netlify hosts the website and may process operational request information. Google Fonts supplies fonts on some pages. Stripe and these providers may process information in other countries under their own terms and arrangements.", "Opening a video player, social link or optional integration can disclose request information or content to that provider. LMR does not control the privacy practices of third-party sites. Read the relevant provider's notice before connecting or sharing sensitive information."] },
      { title: "Access and publication", paragraphs: ["Your account information is used to provide your workspace and support. Registered administrators can access the account, billing and support information their management tools provide. Questions and mentorship requests are directed to LMR; do not treat them as anonymous.", "Member publications are shared according to their configured audience. Administrator observations and achievements are published from the administrator's Journal records when selected for publication. Do not assume that a private message or record is suitable for public sharing. LMR should obtain permission before using a member's identifiable material publicly."] },
      { title: "Retention, security and your requests", paragraphs: ["Information is retained as needed to operate your account, provide support, maintain necessary payment records and meet applicable obligations. Request account deletion or a copy or correction of your information through admin@lmrcapitals.com. Some information may need to be kept for legal, payment or dispute reasons; LMR should explain this when handling a request.", "Authentication and database access controls help protect account data. No online service can promise absolute security. Use a strong, unique password, protect your email account and report suspected unauthorised access promptly.", "If you have a privacy complaint, contact LMR with the details and the outcome you seek. You may also contact the Office of the Australian Information Commissioner about applicable privacy rights and complaint options. This notice does not assert that every provision of the Privacy Act applies to this business."] },
    ],
  },
  risk: {
    title: "Trading risk disclosure", draft: false,
    introduction: "Understand the limits of market education before joining a live room or using a trading example.",
    sections: [
      { title: "Losses and leverage", paragraphs: ["Futures and other leveraged trading involve substantial risk and may not be suitable for you. Leverage can amplify losses; you may lose more than your initial investment. Do not trade with money you cannot afford to lose."] },
      { title: "Education and your decisions", paragraphs: ["LMR content is presented for education and process review. It does not take your personal financial circumstances into account. Observations, commentary, callouts and execution examples are not instructions to place a trade. Seek appropriately licensed independent advice when you need advice about your own situation."] },
      { title: "Performance and examples", paragraphs: ["Past performance is not a reliable indicator of future results. Actual, simulated and hypothetical results must be distinguished. Simulations may not account for liquidity, slippage, fees or the ability to follow a strategy under financial pressure. Achievements are individual examples, not promises of typical results."] },
      { title: "Live information and operational risk", paragraphs: ["Streams and commentary can be delayed, incomplete or interrupted. Prices and market conditions can change rapidly. Verify information independently and use your own risk controls. Membership does not guarantee profits, an accepted mentorship request or uninterrupted streaming."] },
    ],
  },
  community: {
    title: "Inner Circle guidelines", draft: false,
    introduction: "A space to learn the process, ask thoughtful questions and document your own thinking.",
    sections: [
      { title: "Learn before you act", paragraphs: ["Study the terminology chapters in order. Use THE Chain Methodology to understand context, planning, execution and review. Ask why a setup is being discussed rather than treating an observation as an instruction to trade."] },
      { title: "Keep the conversation useful", paragraphs: ["Be respectful. Include the market, session, date and your question when asking for context. Disagreement is welcome; harassment, discriminatory content, spam and impersonation are not. Never ask another member to send money, share credentials or copy your trades."] },
      { title: "Protect personal and paid content", paragraphs: ["Use your own account. Do not share login details, paid recordings or publications outside the membership. Remove account numbers and identifying information from screenshots. Do not publish someone else's private messages or mentorship details without permission."] },
      { title: "Use the right support route", paragraphs: ["Free and paid members can use Q&A for learning questions. Paid members can apply for private mentorship; LMR reviews requests before arranging a session. Use admin@lmrcapitals.com for account, payment, privacy or moderation issues. Include your account email; never send a password, OTP, broker credentials or full card details."] },
    ],
  },
};
