import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { transformWithOxc } from 'vite';
import { registrationDetails, authEmailReturn, onboardingKey, enrollmentReadiness } from '../enrollment.mjs';
import { policies, provider, joiningSteps, accessComparison, guideUrl, policyUrl, policyDraftVersion } from '../guidelines.mjs';
const form = new FormData();
for (const [key, value] of Object.entries({email:' learner@example.com ',name:'Learner',password:'unique-test-password',confirm_password:'unique-test-password',account_terms:'on',risk_acknowledgement:'on'})) form.set(key,value);
const acceptedAt = new Date('2026-10-05T12:00:00Z');
const details = registrationDetails(form, 'approved-test-version', acceptedAt);
assert.equal(details.email, 'learner@example.com');
assert.equal(details.data.legal_accepted_at, acceptedAt.toISOString());
assert.equal(details.data.legal_version, 'approved-test-version');
assert.equal(details.data.risk_acknowledged, true);
assert.equal(details.data.admin, undefined);
assert.equal(details.data.paid, undefined);
for (const missing of ['account_terms','risk_acknowledgement']) {
 form.delete(missing); assert.throws(()=>registrationDetails(form,'approved-test-version'), /Confirm your age/); form.set(missing,'on');
}
form.set('confirm_password','different-password');
assert.throws(()=>registrationDetails(form,'approved-test-version'), /do not match/);
form.set('confirm_password','unique-test-password');
assert.throws(()=>registrationDetails(form, policyDraftVersion), /awaiting approval/);
assert.throws(()=>registrationDetails(form, ''), /awaiting approval/);
form.set('password','short'); assert.throws(()=>registrationDetails(form,'approved-test-version'), /12 characters/);
assert.equal(authEmailReturn('https://lmrcapitals.com'), 'https://lmrcapitals.com/member/index.html');
assert.notEqual(onboardingKey('user-a'), onboardingKey('user-b'));
assert.equal(policyUrl('not-a-policy'), '/inner-circle/guide#start');
assert.equal(provider.entity, 'Individual / sole trader');
assert.match(JSON.stringify(policies.terms), /case by case/);
assert.match(JSON.stringify(policies.terms), /Australian Consumer Law/);
assert.equal(policies.terms.draft, true);
assert.equal(policies.privacy.draft, true);
// Render the actual registration component, so undefined runtime variables cannot ship.
let source = await fs.readFile(new URL('../auth.jsx', import.meta.url), 'utf8');
source = source.replace(/^import .*;\n/gm,'').replace('export default function Auth','function Auth');
const transformed = await transformWithOxc(source,'auth.jsx',{jsx:{runtime:'classic'}});
const Button = ({children,gold,icon,...props}) => React.createElement('button',props,children);
const context = vm.createContext({React,useState:React.useState,useEffect:React.useEffect,Button,Logo:()=>React.createElement('div',null,'LMR Capitals'),location:{search:'?signup=1',origin:'https://lmrcapitals.com'},URLSearchParams,config:{legalVersion:'',termsUrl:'',privacyUrl:''},accountRegistrationReady:false,sb:null,guideUrl,policyUrl,provider,registrationDetails,authEmailReturn});
vm.runInContext(transformed.code + '\nthis.AuthForTest = Auth;',context);
let html = renderToStaticMarkup(React.createElement(context.AuthForTest,{onLegal:()=>{}}));
assert.match(html, /Create free account/);
assert.match(html, /name="confirm_password"/);
assert.match(html, /name="account_terms"/);
assert.match(html, /name="risk_acknowledgement"/);
assert.match(html, /href="\/inner-circle\/guide#terms"/);
assert.match(html, /href="\/inner-circle\/guide#privacy"/);
assert.match(html, /disabled=""/);
assert.match(html, /awaiting final policy approval/);
context.location.search='';
html=renderToStaticMarkup(React.createElement(context.AuthForTest,{onLegal:()=>{}}));
assert.match(html,/Sign in to Inner Circle/);
assert.doesNotMatch(html,/name="confirm_password"/);
assert.ok(joiningSteps.length===5);
assert.ok(accessComparison.some(row=>row[0]==='Administrator Hub' && row[2]==='Administrator only'));
const publicPolicies={legalVersion:'2026-10-05',termsUrl:'https://lmrcapitals.com/inner-circle/guide#terms',privacyUrl:'https://lmrcapitals.com/inner-circle/guide#privacy',accountPoliciesApproved:true,legalApproved:false};
assert.deepEqual(enrollmentReadiness(publicPolicies),{account:true,paid:false},'Approving free registration must never enable payments');
assert.deepEqual(enrollmentReadiness({...publicPolicies,legalVersion:policyDraftVersion}),{account:false,paid:false});
assert.deepEqual(enrollmentReadiness({...publicPolicies,termsUrl:'javascript:alert(1)'}),{account:false,paid:false});
assert.deepEqual(enrollmentReadiness({...publicPolicies,legalApproved:true}),{account:true,paid:true});
console.log('Enrollment acknowledgement, policy gates, account isolation and actual registration/sign-in rendering passed.');
